export const payroll = [
  {
    id: 1,
    payroll: {
      id: 1,
      ref_no: "PR-0001",
      date_from: "2024-01-01",
      date_to: "2024-01-15",
      type: "Semi-Monthly",
      status: "Completed",
    },
    employee: {
      id: 1,
      name: "John Doe",
      position: "Software Engineer",
      department: "IT",
    },
    present: 60,
    absent: 0,
    late: 2,
    salary: 5000,
    allowance_amount: 500,
    deduction_amount: 200,
    net: 5300,
  },
  {
    id: 2,
    payroll: {
      id: 2,
      ref_no: "PR-0002",
      date_from: "2024-01-16",
      date_to: "2024-01-31",
      type: "Semi-Monthly",
      status: "Pending",
    },
    employee: {
      id: 2,
      name: "Jane Smith",
      position: "Project Manager",
      department: "Operations",
    },
    present: 59,
    absent: 1,
    late: 0,
    salary: 6000,
    allowance_amount: 600,
    deduction_amount: 300,
    net: 6300,
  },
  {
    id: 3,
    payroll: {
      id: 3,
      ref_no: "PR-0003",
      date_from: "2024-02-01",
      date_to: "2024-02-15",
      type: "Semi-Monthly",
      status: "Completed",
    },
    employee: {
      id: 3,
      name: "Mark Johnson",
      position: "HR Manager",
      department: "Human Resources",
    },
    present: 60,
    absent: 0,
    late: 1,
    salary: 5500,
    allowance_amount: 550,
    deduction_amount: 250,
    net: 5800,
  },
  {
    id: 4,
    payroll: {
      id: 4,
      ref_no: "PR-0004",
      date_from: "2024-02-16",
      date_to: "2024-02-29",
      type: "Semi-Monthly",
      status: "Pending",
    },
    employee: {
      id: 4,
      name: "Emily Davis",
      position: "Marketing Specialist",
      department: "Marketing",
    },
    present: 58,
    absent: 2,
    late: 0,
    salary: 4800,
    allowance_amount: 480,
    deduction_amount: 220,
    net: 5060,
  },
  {
    id: 5,
    payroll: {
      id: 5,
      ref_no: "PR-0005",
      date_from: "2024-03-01",
      date_to: "2024-03-15",
      type: "Semi-Monthly",
      status: "Completed",
    },
    employee: {
      id: 5,
      name: "Sophia Lee",
      position: "Data Scientist",
      department: "IT",
    },
    present: 62,
    absent: 0,
    late: 0,
    salary: 7000,
    allowance_amount: 700,
    deduction_amount: 300,
    net: 7400,
  },
  {
    id: 6,
    payroll: {
      id: 6,
      ref_no: "PR-0006",
      date_from: "2024-03-16",
      date_to: "2024-03-31",
      type: "Semi-Monthly",
      status: "Pending",
    },
    employee: {
      id: 6,
      name: "James Wilson",
      position: "Financial Analyst",
      department: "Finance",
    },
    present: 60,
    absent: 0,
    late: 1,
    salary: 6500,
    allowance_amount: 650,
    deduction_amount: 200,
    net: 6950,
  },
  {
    id: 7,
    payroll: {
      id: 7,
      ref_no: "PR-0007",
      date_from: "2024-04-01",
      date_to: "2024-04-15",
      type: "Semi-Monthly",
      status: "Completed",
    },
    employee: {
      id: 7,
      name: "David Brown",
      position: "Software Engineer",
      department: "IT",
    },
    present: 60,
    absent: 0,
    late: 0,
    salary: 5500,
    allowance_amount: 500,
    deduction_amount: 250,
    net: 5750,
  },
  {
    id: 8,
    payroll: {
      id: 8,
      ref_no: "PR-0008",
      date_from: "2024-04-16",
      date_to: "2024-04-30",
      type: "Semi-Monthly",
      status: "Pending",
    },
    employee: {
      id: 8,
      name: "Olivia Taylor",
      position: "Content Writer",
      department: "Marketing",
    },
    present: 58,
    absent: 1,
    late: 0,
    salary: 4800,
    allowance_amount: 450,
    deduction_amount: 200,
    net: 5050,
  },
  {
    id: 9,
    payroll: {
      id: 9,
      ref_no: "PR-0009",
      date_from: "2024-05-01",
      date_to: "2024-05-15",
      type: "Semi-Monthly",
      status: "Completed",
    },
    employee: {
      id: 9,
      name: "Liam Martinez",
      position: "Sales Manager",
      department: "Sales",
    },
    present: 61,
    absent: 0,
    late: 1,
    salary: 6300,
    allowance_amount: 600,
    deduction_amount: 250,
    net: 6650,
  },
  {
    id: 10,
    payroll: {
      id: 10,
      ref_no: "PR-0010",
      date_from: "2024-05-16",
      date_to: "2024-05-31",
      type: "Semi-Monthly",
      status: "Pending",
    },
    employee: {
      id: 10,
      name: "Isabella Green",
      position: "UX Designer",
      department: "Design",
    },
    present: 59,
    absent: 1,
    late: 0,
    salary: 5200,
    allowance_amount: 480,
    deduction_amount: 250,
    net: 5430,
  },
];
